# This file was generated by GoReleaser. DO NOT EDIT.
class Epsg < Formula
  desc "A command-line-tool to convert coordinates between epsg codes."
  homepage "https://github.com/wroge/epsg/tree/master/epsg"
  url "https://github.com/wroge/epsg/releases/download/v1.0.0/epsg_1.0.0_MacOS_x86_64.tar.gz"
  version "1.0.0"
  sha256 "c55acf1b4cb52cc1ea9c8e39060dacde1d714bc2bc1167228c1f29ec50600204"

  def install
    bin.install "epsg"
  end
end
