# This file was generated by GoReleaser. DO NOT EDIT.
class Epsg < Formula
  desc "A command-line-tool to convert coordinates between epsg codes."
  homepage "https://github.com/wroge/epsg/tree/master/epsg"
  url "https://github.com/wroge/epsg/releases/download/v1.0.0/epsg_1.0.0_MacOS_x86_64.tar.gz"
  version "1.0.0"
  sha256 "c614f86a499d3ae03783670dd91f932df0f89f304bac5543cf6a95d4ee383f80"

  def install
    bin.install "epsg"
  end
end
