# This file was generated by GoReleaser. DO NOT EDIT.
class Epsg < Formula
  desc "A command-line-tool to convert coordinates between epsg codes."
  homepage "https://github.com/wroge/epsg/tree/master/epsg"
  url "https://github.com/wroge/epsg/releases/download/v1.0.5/epsg_1.0.5_MacOS_x86_64.tar.gz"
  version "1.0.5"
  sha256 "8773e92bce4f16ce1f625a760b0e64aa40bb43567740046a40a1bb9580f2b095"

  def install
    bin.install "wms"
  end
end
