# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wms < Formula
  desc "A command-line-tool to simplify the use of Web Map Services."
  homepage "https://github.com/wroge/wms"
  version "0.0.17"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wroge/wms/releases/download/v0.0.17/wms_Darwin_x86_64.tar.gz"
      sha256 "8ffc1fdf7e56db5637c0e542a70185ddcd7ef3a54fd5cc4f010d2d174457e83e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/wroge/wms/releases/download/v0.0.17/wms_Darwin_arm64.tar.gz"
      sha256 "a7b11f07171fd9e438e7afef051f8d2eb2737a80310480cf1d63db82e48277cb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wroge/wms/releases/download/v0.0.17/wms_Linux_x86_64.tar.gz"
      sha256 "ab5d43b28076184a48704811583dadda2ad0ca96b36d3353a6676353d7b2a9e1"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/wroge/wms/releases/download/v0.0.17/wms_Linux_armv6.tar.gz"
      sha256 "62590fe2aae6645850472fe1aca693e2a2538479dfefabd701f67cc994e47a60"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wroge/wms/releases/download/v0.0.17/wms_Linux_arm64.tar.gz"
      sha256 "fb1d5cbe076887d3ec40389fdb8ae245d7b1426b13fb4a378e57f72fd136aa2b"
    end
  end

  def install
    bin.install "wms"
  end
end
