# This file was generated by GoReleaser. DO NOT EDIT.
class Wms < Formula
  desc "Extension for easy use of Web Map Services."
  homepage "https://github.com/wroge/wms"
  url "https://github.com/wroge/wms/releases/download/v0.0.12/wms_0.0.12_MacOS_x86_64.tar.gz"
  version "0.0.12"
  sha256 "8623e98342de03a05d8506992322733504c5c2ca53ccacb29378faf85c86d8ab"

  def install
    bin.install "wms"
  end
end
